# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"example_function": "00_core.ipynb"}

modules = ["core.py"]

doc_url = "https://mgloder.github.io/some_lib_name/"

git_url = "https://github.com/mgloder/some_lib_name/tree/{branch}/"

def custom_doc_links(name): return None
